Changed node/client cleanup timing so that test will be done on created instances.

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -53,6 +53,11 @@ jobs:
     runs-on: self-hosted
     needs: Push-Policyfile
     steps:
+      - name: Cleaning up previous AWS 
+        run: |
+          knife node list -c .chef/config.rb | grep "aws" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
+          knife client list -c .chef/config.rb | grep "aws" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
+      
       - name: Running Terraform
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -61,8 +66,6 @@ jobs:
         run: |
           terraform init
           terraform apply -auto-approve
-          knife node list -c .chef/config.rb | grep "aws" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
-          knife client list -c .chef/config.rb | grep "aws" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
           
   Inspec-Test:
     runs-on: self-hosted
